config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "index#page"

  # Landing page
  get "/", to: "index#page", as: "index"
  # Pages
  get "/contact", to: "pages#contact", as: "contact"
  post "/contact/send_email", to: "pages#send_email", as: "send_email"

  get "/testing", to: "pages#testing", as: "testing"
  get "/testing_two", to: "pages#testing_two", as: "testing_two"
  
  get "/car/:car_id", to: "pages#car", as: "car"
  # Dashboard
  get "/dashboard", to: "dashboard#page", as: "dashboard"
  # User Management
  patch "/dashboard/update_user", to: "dashboard#update_user", as: "update_user"
  # Cars Management
  post "/dashboard/create_car", to: "dashboard#create_car", as: "create_car"
  
  get "/dashboard/edit_car/:car_id", to: "dashboard#edit_car", as: "edit_car"
  patch "/dashboard/update_car", to: "dashboard#update_car", as: "update_car"
  patch "/dashboard/edit_car/:car_id/set_default_img/:image_id", to: "dashboard#set_default_img", as: "set_default_img"
  delete "/dashboard/delete_car", to: "dashboard#delete_car", as: "delete_car"
  # images
  post "/dashboard/create_image", to: "dashboard#create_image", as: "create_image"
  delete "/dashboard/delete_image", to: "dashboard#delete_image", as: "delete_image"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
    include CarManager
    include ImageManager
    include UserManager
    def page
        @user = current_user
        @cars = Car.all
        render :dashboard
    end

    def edit_car
        @car = Car.find(params[:car_id])
        render :edit_car
    end

    #region dashboard
# User ----------------------------------------------------------------------------------------------------------------
    def update_user
        unless (params[:location].blank? && params[:location_link]) || (params[:location].present? && params[:location_link].present?)
            flash[:alert] = "Please provide either both a location and a location link, or neither."
            redirect_to dashboard_path and return
        end
        
        if edit_selected_user
            flash[:notice] = "User updated successfully."
            redirect_to dashboard_path
        else
            flash[:alert] = @user.errors.full_messages.to_sentence
            redirect_to dashboard_path
        end
    end


    # Car ----------------------------------------------------------------------------------------------------------------

    def create_car
        if create_new_car
            flash[:notice] = "Car created successfully."
            redirect_to dashboard_path
        else
            flash[:alert] = @car.errors.full_messages.to_sentence
            redirect_to dashboard_path
        end
    end

    def update_car 
        if edit_selected_car
            flash[:notice] = "Car updated successfully."
            redirect_to edit_car_path(car_id: @car.id)
        else
            flash[:alert] = @car.errors.full_messages.to_sentence
            redirect_to edit_car_path(car_id: @car.id)
        end
    end

    def set_default_img
        @car = Car.find(params[:car_id])
        @image = Image.find(params[:image_id])
        if @car.update(display_image: @image.id)
            flash[:notice] = "Default image set successfully."
            redirect_to edit_car_path(car_id: @car.id)
        else
            flash[:alert] = @car.errors.full_messages.to_sentence
            redirect_to edit_car_path(car_id: @car.id)
        end
    end
    
    def delete_car
        if delete_selected_car
            flash[:notice] = "Car deleted successfully."
            redirect_to dashboard_path
        else
            flash[:alert] = @car.errors.full_messages.to_sentence
            redirect_to dashboard_path, alert: "Failed to delete car."
        end
    end

# ----------------------------------------------------------------------------------------------------------------

# Image ----------------------------------------------------------------------------------------------------------------
    def create_image
        @car = Car.find(params[:car_id])
        uploaded_file = params[:image]

        unless uploaded_file.present?
            flash[:alert] = "No file selected for upload."
            redirect_to edit_car_path(car_id: @car.id) and return
        end
        
        if create_new_image(uploaded_file, @car.id)
            flash[:notice] = "Image uploaded successfully."
            redirect_to edit_car_path(car_id: @car.id)
        else
            flash[:alert] = @image.errors.full_messages.to_sentence
            redirect_to edit_car_path(car_id: @car.id)
        end
    end

    def delete_image 
        @image = Image.find(params[:image_id])
        if delete_selected_image(@image)
            flash[:notice] = "Image deleted successfully."
            redirect_to edit_car_path(car_id: @car.id)
        else
            flash[:alert] = @image.errors.full_messages.to_sentence
            redirect_to edit_car_path(car_id: @car.id)
        end
    end

 
      
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/dashboard.html.erb
<div class = "space"></div>
<div class="dashboard">

  <div class = "page-nav">
    <div class = "website-title">
      <h1><%= link_to "ExoticEuro", root_path, style: "text-decoration: none; color: inherit; font-size: 3rem;" %></h1>
    </div>

    <div class = "page-title">
      <h1> Dashboard </h1>
    </div>
  </div>

  <div class='form-card'>
    <h2> Update User</h2>
    <%= form_with(url: update_user_path(user_id: @user.id), local: true, method: :patch) do |form| %>
      <div class = "form-column">
        <%= form.label :display_email, "Display Email" %>
        <%= form.text_field :display_email, value: @user.display_email, placeholder: "Enter Email For People to see " %>
      </div>

      <h3> Contact Page Information</h3>
      <div class = "form-column">
        <%= form.label :phone %>
        <%= form.text_field :phone, value: @user.phone %>
      </div>
      <div class = "form-column">
        <%= form.label :contact_email, "Contact Form Email" %>
        <%= form.text_field :contact_email, value: @user.contact_email, placeholder: "Set up Email for the Contact form" %>
      </div>
      
      <h3> Location Information</h3>
      <div class = "form-column">
        <%= form.label :location, "Location Address" %>
        <%= form.text_field :location, value: @user.location, placeholder: "Enter the Address 8321 something something" %>
      </div>
      <div class = "form-column">
        <%= form.label :location_link, "Location Link" %>
        <%= form.text_field :location_link, value: @user.location_link, placeholder: "Enter Link from Google Maps" %>
      </div>

      <h3> Social Media Links</h3>
      <div class = "form-column">
        <%= form.label :youtube %>
        <%= form.text_field :youtube, value: @user.youtube %>
      </div>
      <div class = "form-column">
        <%= form.label :facebook %>
        <%= form.text_field :facebook, value: @user.facebook %>
      </div>
      <div class = "form-column">
        <%= form.label :instagram %>
        <%= form.text_field :instagram, value: @user.instagram %>
      </div>

      <h3> About Page Information</h3>
      <div class = "form-column">
        <%= form.label :bio, "About Info" %>
        <%= form.text_area :bio,
              rows: 10,          # height  (lines)
              cols: 60,          # width   (characters)
              value: @user.about %>
      </div>
      
      <div class = "form-column">
        <%= form.submit "Update User" %>
      </div>
    <% end %>
  </div>

  <div class = 'form-card'>
    <h2> Add New Car</h2>
    <%= form_with(url: create_car_path, local: true, html: { multipart: true }) do |form| %>
      <div class = "form-column"> 
        <%= form.label :car_make, "Make" %>
        <%= form.text_field :car_make, required: true %>
      </div>

      <div class = "form-column">
        <%= form.label :car_model, "Model" %>
        <%= form.text_field :car_model, required: true %>
      </div>

      <div class = "form-column">
        <%= form.label :price %>
        <%= form.number_field :price, step: 0.01, required: true %>
      </div>

      <div class = "form-column">
        <%= form.label :year, "Year of Manufacture" %>
        <%= form.number_field :year, step: 1, required: true %>
      </div>

      <div class = "form-column">
        <%= form.label :compared_price %>
        <%= form.number_field :compared_price, step: 0.01, placeholder: "Enter the price you want to compare with" %>
      </div>

      <div class = "form-column">
        <%= form.label :miles, "Mileage" %>
        <%= form.number_field :miles, step: 1, required: true %>
      </div>

      <div class = "form-column" >
        <%= form.label :description %>
        <%= form.text_area :description, rows: 5, cols: 60, required: true %>
      </div>

      <div class = "form-column">
        <%= form.label :link, "External Link" %>
        <%= form.text_field :link, placeholder: "Enter a link to the car's page" %>
      </div>

      <div class = "form-column">
        <%= form.label :images, "Upload Car Images" %>
        <%= file_field_tag "car[image]", accept: ".png,.jpg,.jpeg", required: true %>
      </div>

      <div class = "form-column">
        <%= form.submit "Create Car" %>
      </div>
    <% end %>
  </div>


  <div>
    <% if @cars.present? %>
      <h2 style = "color: white; text-align: center">All Cars</h2>
      <% no_image = Image.find_by(name: "no_image") %>

      <% @cars.each do |car| %>
        <%= link_to edit_car_path(car_id: car.id), class: "car-link" do %>
          <% if car.images.any? %>
            <div class="car-card" style="background-image: url('<%= car.images.first.url %>'); background-size: cover; background-position: center;">
              <h3><%= car.car_make %> <%= car.car_model %></h3>
            </div>
          <% else %>
            <div class="car-card" style="background-image: url('<%= no_image&.url %>'); background-size: cover; background-position: center;">
              <h3><%= car.car_make %> <%= car.car_model %></h3>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <h2>No Cars Available</h2>
    <% end %>
  </div>
</div>
<style>
    .car-card {
        border: 1px solid #ccc;
        width: 300px;
        height: 150px;
        padding: 10px;
        margin: 10px;
        border-radius: 20px;
        overflow: hidden;
    }

    .car-card h3 {
        color: black;
        background: blur(10px);
        text-align: center;
        font-size: 2rem;
        margin-top: 10px;
        word-wrap: break-word; /* Wrap text to the next line if it's too long */
        overflow-wrap: break-word; /* Ensure compatibility for wrapping */
        white-space: normal; /* Allow text to wrap */
        font-size: clamp(1rem, 2vw, 2rem); /* Scale font size responsively */
    }


</style>

app/views/dashboard/edit_car.html.erb
  <div class = "page-nav" style = "color: white;">
    <div class = "website-title">
      <h1><%= link_to "ExoticEuro", root_path, style: "text-decoration: none; color: inherit; font-size: 3rem;" %></h1>
    </div>

    <div class = "page-title">
      <h1> Car Info </h1>
    </div>
  </div>

<% if @car.present?%>
    <a> <%= button_to "Back to Dashboard", dashboard_path, method: :get, class: "book-btn" %></a>
    <a> <%= button_to "Delete Car", delete_car_path(car_id: @car.id), method: :delete, class: "delete-btn" %></a>

    <div class = "form-card">
   <%= form_with( url: update_car_path(car_id: @car.id), local: true, method: :patch) do |form| %>
        <div class='form-column'>
            <%= form.label :car_make, "Make" %>
            <%= form.text_field :car_make, value: @car.car_make %>
        </div>

        <div class='form-column'>
            <%= form.label :car_model, "Model" %>
            <%= form.text_field :car_model, value: @car.car_model %>
        </div>

        <div class='form-column'>
            <%= form.label :price %>
            <%= form.number_field :price, step: 0.01, value: @car.price %>
        </div>

        <div class='form-column'>
            <%= form.label :year, "Year of Manufacture" %>
            <%= form.number_field :year, step: 1, value: @car.year %>
        </div>

        <div class='form-column'>
            <%= form.label :compared_price, "Market Price" %>
            <%= form.number_field :compared_price, step: 0.01, value: @car.compared_price %>
        </div>

        <div class='form-column'>
            <%= form.label :miles, "Mileage" %>
            <%= form.number_field :miles, value: @car.miles %>
        </div>

        <div class='form-column'>
            <%= form.label :description %>
            <%= form.text_area :description, value: @car.description %>
        </div>

        <div class='form-column'>
            <%= form.label :link, "External Link" %>
            <%= form.text_field :link, value: @car.link %>
        </div>

        <div class='form-column'>
            <%= form.submit "Update Car" %>
        </div>

    <% end %>

    <h2> Upload New Car Image</h2>
    <%= form_with(url: create_image_path(car_id: @car.id), local: true,multipart: true) do |form| %>
        <div>
            <%= form.label :image, "Upload Car Images" %>
            <%= file_field_tag "image", accept: "image/*", required: true  %>
        </div>

        <div>
            <%= form.submit "Upload Image" %>
        </div>
    <% end %>
</div>

    <% if @car.images.any? %> 
      <% @car.images.each do |image| %> 
        <div class="car-image" style="background-image: url('<%= image.url %>'); background-size: cover; background-position: center;">
            <%= button_to "Delete Image", delete_image_path(image_id: image.id), method: :delete, class: "delete-btn" %>
            <% if image.id != @car.display_image.to_i %>
                <%= button_to "Set as Default", set_default_img_path(image_id: image.id), method: :patch, class: "delete-btn", style: "background-color: green" %>
            <% end %>
        </div>
      <% end%> 
    <% end%>

<% else %>
    <h1> No Car Found</h1>
<% end %>